### ISSUE TITLE
Help with numbers in limiting cues ms!

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#394] opened 2021-02-01 23:12 UTC
@cchambe12 

Can you help me update the text in 'How studies and their experimental treatments vary globally' and 'How studies manipulate cues'? I ask because I think to do this requires your code in studydesign_numcues.R and my code in countintxns.R and I am a bit overwhelmed by the task. To make it easier though I have added to countintxns.R new output ospree_studyinxns.csv ... this *should* be every interactive study labeled with its interaction. I wondered if between this and your studytype_table.csv you could write new code (in one of the relevant current files or make a new one) you could write code that gets all the numbers currently in those sections of the manuscript *and* provide a little more on the single cue studies (which cues get manipulated? Any other relevant info? Once we have that I can update that ADDINFO spot in the ms.

See also issue #249

**Comment by cchambe12** [comment] 2021-02-08 19:43
@lizzieinvancouver I think I am done with this task! I have added key codes to countintxns.R so we can use these in the manuscript. I'd be happy to put these codes in the .Rnw file if you'd like that too!

One question I have, at the end of page 8 you say:
 "A slightly larger set of studies (5 studies) examined three cues indirectly—manipulating photoperiod and forcing in controlled environments but equating chilling with sequential removal of tissue from the field—for 11 species (Schnabel & Wample, 1987; Heide, 1993a; Partanen et al., 1998; Basler & K ̈orner, 2014)." 

But only 4 studies are cited, is the fifth skuterud94?

**Comment by cchambe12** [comment] 2021-02-08 19:46
@lizzieinvancouver Also, I realized the studydesign_numcues.R was only using studies from the bb_analysis so I have updated Figure 6 to include all studies

**Comment by lizzieinvancouver** [comment] 2021-02-10 01:43
@cchambe12 Amazing! Thank you! 

Good point on the five studies ... looking at ospree_studyinxns.csv I think we may need to double check ... 

* skuterud94 -- looks to be exp chill 
*  schnabel87 and partanen98 I have listed as photo/force x field sample ... meaning I thought photo and force covary (not full factorial)

Can you check these papers to see if you agree or disagree?

Also, it would be *wonderful* if you could put the codes in an .Rnw -- I have had setting up sweave for the main text and supp as a todo item for so long, so this would be a good push for me.

**Comment by cchambe12** [comment] 2021-02-10 18:28
@lizzieinvancouver Ahh yes, skuterud94 is experimental chill and yes again to schnaebel and partenen98, photo and forcing covary for sure. 

Okay, I have added a new .Rnw. I hope it works, I think your compilation system is different than mine and I didn't want to mess up your .pdf or .tex files.

**Comment by lizzieinvancouver** [comment] 2021-02-15 02:41
@cchambe12 The .Rnw compiled for me without a hitch -- amazing! Thank you!

Your code looks great, but I do have a few more requests before I finalize a new draft. If any of these are tricky or onerous, let me know and I can try to help.

1. Can you estimate the counts of studies by datasetID x study? I think that is how I did many of the counts but it looks lookupintxns and lookupcues might be on datasetID only. Especially for cues I think the study is the relevant unit.
2. For the single cue studies, can you estimate how many are forcing, photo or chilling?
3. Can you estimates for the number of studies manipulating at least one cue, and then manipulating another cue (for the line, "Of the studies manipulating at least one cue, half additionally manipulated another cue") and then how that, how many were interactive?
4. In the paragraph starting, "Studies examining three cues directly were very rare..." can you check where skuterud94 should be?

I think that's it. I am sorry this is such a pain, but I cannot tell you how much I appreciate your help!

**Comment by cchambe12** [comment] 2021-02-15 18:27
@lizzieinvancouver  No problem at all! I have made the above corrections.  I have not added these new codes into the .Rnw as I'm not sure where or how you want to include them and I didn't want to change the text too much. Let me know if you'd like me to do that for you though! 

1. I have added "study" to both of these lookups
2. I have added these and have named them as "num.force.single", "num.photo.single", "num.chill.single"
3. I have added "num.force.all", "num.photo.all", "num.chill.all" for all of the studies manipulating at least one cue. I have added "num.twocues.all" value for the studies manipulating a second cue and finally a "num.twocues.intxn" value for how many of those are interactive. I have also added a "num.twocues.single" value for the number of studies manipulating two cues but are not interactive.
4. I have updated this line to say "Studies examining three cues directly were very rare: we identified only three studies examining all three cues at once\citep{Worrall:1967aa,Skuterud:1994aa,Sogaard:2008aa}, and two of which were on \emph{Picea abies} \citep{Worrall:1967aa,Sogaard:2008aa}. "

**Comment by lizzieinvancouver** [comment] 2021-02-15 21:48
@cchambe12 Thank you! I put most of these in, but the numbers don't always line up:

Re 2. Can you check how these are estimated? The numbers seem like the should add up (or close to) but they way over-add-up, here's how they print: "Single cue studies were the most common (64 studies), with 41 manipulating forcing, 40 manipulating photoperiod and 34 manipulating chilling."

Re 3: Similar issues here, it 75 studies manipulated two cues, then "69 studies designed experiments to test [interactive cues] while 33 studies did not"

Let me know if I can help! I think headaches like these are why I spun my wheels for a year in trying to update this paper.

**Comment by cchambe12** [comment] 2021-02-17 20:16
@lizzieinvancouver I think this is an issue when we use "study" as well as datasetID. Since there are only 85 datasetIDs, they seem to not add up but when we add in "study" they won't exactly add up and some datasetIDs will be represented as interactive studies and also as single cue studies depending on the different experiments they performed. 

As for Re 2., these won't add up because many studies are in fact single cue studies but they also manipulate an additional cue. I can recalculate these to only include "datasetID" for the lookupintxns and lookupcues dataframes if you'd like?

**Comment by lizzieinvancouver** [comment] 2021-02-18 20:39
@cchambe12 Thanks for working on this. Do you think I can fix it by always using DatasetID and study together? It seems to me like that should work unless I am missing something? I think we should focus mainly on DatasetIDxstudy as that's the unit at which treatments are applied. 

What do you mean by "many studies are in fact single cue studies but they also manipulate an additional cue"?

**Comment by cchambe12** [comment] 2021-02-19 15:09
@lizzieinvancouver Okay, I think I have fixed the issues. I guess what I mean is that not all of the numbers will add up entirely because some studies manipulate more than one cue but they weren't interactive studies. But I think it is fixed now.

**Comment by lizzieinvancouver** [comment] 2021-02-19 19:30
@cchambe12 Yes! That's something we'll probably have to work on in the ms. I tried running the code but `num.twocues.intxn` is commented out, though we use it in text. Do you know an easy way to re-create it? Otherwise I can go through the code and work on it this weekend.

**Comment by cchambe12** [comment] 2021-02-19 20:02
@lizzieinvancouver oh sorry about that! All fixed now!

**Comment by lizzieinvancouver** [comment] 2021-02-20 21:55
@cchambe12  Thanks! The numbers still seemed weird so I went through the code and found a few things. I am still working on it, but here's what I have so far ... I need more help including a sanity check ...

I think something like this: `lookupcueintxns$force>1 & lookupcueintxns$photo>1 ` may select MORE than we mean to (I think) so I switched to:
``
twocuesdf <- lookupcueintxns[((lookupcueintxns$force>1 & lookupcueintxns$photo>1 & lookupcueintxns$chill<2) |
    (lookupcueintxns$force>1 &  lookupcueintxns$photo<2 & lookupcueintxns$chill>1) |
    (lookupcueintxns$force<2 & lookupcueintxns$photo>1 & lookupcueintxns$chill>1)),]
```

Also, why delete these?

```cues <- cues[!(cues$datasetID=="granhus09" | cues$datasetID=="rinne94" | cues$datasetID=="spann04"),]
```
I think perhaps because they are about bud dormancy? If so we should delete them AS SOON AS we read in the files, and need to do it ACROSS all files. I did this for spann04, but I sort of think the other two are okay. What do you think? I am just guessing why you deleted them. 

Also, there's a merge and then a lot of deleting stuff that I don't understand. Can you comment in why you do this? Is it possible to avoid the deletions perhaps by not using all.x and all.y == TRUE (that is, if one file has the RIGHT answer then we can keep just that one ... if it's the first file you do all.x=TRUE and all.y=FALSE ... but maybe it's not like that?).

Either way, this code is not study-specific so we lose a lot of studies along the way and our numbers get off ....

```
cues <- cues[!(cues$datasetID=="sogaard08" & cues$numcues==0),]
cues <- cues[!(cues$datasetID=="guerriero90" & cues$numcues==0 & cues$field.sample==1),]
cues <- cues[!(cues$datasetID=="spiers74" & cues$numcues==0 & cues$field.sample==1),]
cues <- cues[!(cues$datasetID=="worrall67" & cues$numcues==0 & cues$prov.lat==1),]
cues <- cues[!(cues$datasetID=="falusi97" & cues$numcues==0),]
cues <- cues[!(cues$datasetID=="jones12" & cues$numcues==0),]
cues <- cues[!(cues$datasetID=="sonsteby14" & cues$numcues==0),]
cues <- cues[!(cues$datasetID=="thielges" & cues$numcues==0),]
```

Right now I am updating this with some guesses so we keep more studies, but I'll need your help next week to try to fix it more. More updates to come. 

You definitely got the hardest task so I appreciate your help!

**Comment by lizzieinvancouver** [comment] 2021-02-21 03:53
@cchambe12 Ahh! I think we're thinking of single cues differently

singlecues <- lookupintxns[(lookupintxns$interaction==0),]

Will give studies without interactions, but they could manipulate more than one cue!

**Comment by lizzieinvancouver** [comment] 2021-02-21 03:54
Saving a bunch of code I wrote and may not need ....

```
# ospintxnstudiesall has studies appearing in more than one row ... (for example, basler14, exp1)
# Let's fix that ...
ospintxnstudiesalldups <- ospintxnstudiesall
ospintxnstudiesalldups$intxn <- NULL
subset(aggregate(ospintxnstudiesalldups["interaction"], ospintxnstudiesalldups[c("datasetID", "study")], FUN=sum), interaction>1)

length(unique(paste(ospintxnstudiesalldups$datasetID, ospintxnstudiesalldups$study)))

ospintxnstudiesallnodup <- ospintxnstudiesall
ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="worrall67" &
    ospintxnstudiesallnodup$study=="exp 3" & ospintxnstudiesallnodup$intxn=="force x chilldays"),]
ospintxnstudiesallnodup$intxn[which(ospintxnstudiesallnodup$datasetID=="worrall67" &
    ospintxnstudiesallnodup$study=="exp 3" & ospintxnstudiesallnodup$intxn=="photo x chilldays")] <-
    "force/photo x chilldays"

ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="basler14" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="force x photo"),] 
ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="basler14" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="force x fieldsample dates"),]
ospintxnstudiesallnodup$intxn[which(ospintxnstudiesallnodup$datasetID=="basler14" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="photo x fieldsample dates")] <-
    "force x photo x fieldsample dates"

ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="falusi90" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="photo x chilltemp"),] 
ospintxnstudiesallnodup$intxn[which(ospintxnstudiesallnodup$datasetID=="falusi90" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="photo x chilldays")] <-
    "photo x chilltemp/chilldays"

ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="heide12" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="photo x chilltemp"),] 
ospintxnstudiesallnodup$intxn[which(ospintxnstudiesallnodup$datasetID=="heide12" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="photo x chilldays")] <-
    "photo x chilltemp/chilldays"

ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="heide93" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="force x photo"),]
ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="heide93" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="force x fieldsample dates"),] 
ospintxnstudiesallnodup$intxn[which(ospintxnstudiesallnodup$datasetID=="heide93" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="photo x fieldsample dates")] <-
    "force x photo x fieldsample dates"

ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="myking95" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="photo x chilltemp"),] 
ospintxnstudiesallnodup$intxn[which(ospintxnstudiesallnodup$datasetID=="myking95" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="photo x chilldays")] <-
    "photo x chilltemp/chilldays"

ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="partanen98" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="force x fieldsample dates"),]
ospintxnstudiesallnodup$intxn[which(ospintxnstudiesallnodup$datasetID=="partanen98" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="photo x fieldsample dates")] <-
    "force/photo x fieldsample dates"

ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="schnabel87" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="force x fieldsample dates"),]
ospintxnstudiesallnodup$intxn[which(ospintxnstudiesallnodup$datasetID=="schnabel87" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="photo x fieldsample dates")] <-
    "force/photo x fieldsample dates"

ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="skuterud94" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="force x chilltemp"),]
ospintxnstudiesallnodup$intxn[which(ospintxnstudiesallnodup$datasetID=="skuterud94" &
    ospintxnstudiesallnodup$study=="exp1" & ospintxnstudiesallnodup$intxn=="force x chilldays")] <-
    "force x chilldays/chilltemp"

ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="heide93" &
    ospintxnstudiesallnodup$study=="exp2" & ospintxnstudiesallnodup$intxn=="force x photo"),]
ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="heide93" &
    ospintxnstudiesallnodup$study=="exp2" & ospintxnstudiesallnodup$intxn=="force x fieldsample dates"),] 
ospintxnstudiesallnodup$intxn[which(ospintxnstudiesallnodup$datasetID=="heide93" &
    ospintxnstudiesallnodup$study=="exp2" & ospintxnstudiesallnodup$intxn=="photo x fieldsample dates")] <-
    "force x photo x fieldsample dates"

ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="okie11" &
    ospintxnstudiesallnodup$study=="exp2" & ospintxnstudiesallnodup$intxn=="force x photo"),]
ospintxnstudiesallnodup <- ospintxnstudiesallnodup[-which(ospintxnstudiesallnodup$datasetID=="okie11" &
    ospintxnstudiesallnodup$study=="exp2" & ospintxnstudiesallnodup$intxn=="force x chilldays"),] 
ospintxnstudiesallnodup$intxn[which(ospintxnstudiesallnodup$datasetID=="okie11" &
    ospintxnstudiesallnodup$study=="exp2" & ospintxnstudiesallnodup$intxn=="photo x chilldays")] <-
    "force x photo x chilldays"

length(unique(paste(ospintxnstudiesallnodup$datasetID, ospintxnstudiesallnodup$study)))

     
```

**Comment by lizzieinvancouver** [comment] 2021-02-21 04:15
Some of Cat's code I am deleting, but again saving for fear we may want it ...


```
if(FALSE){ # C
# I think we must have varying cues by species in a few studies, so we need to get down to one
# answer of cues per study 
cues <- cues[!(cues$datasetID=="sogaard08" & cues$study=="exp1b" & cues$numcues==0),]
cues <- cues[!(cues$datasetID=="sogaard08" & cues$study=="exp2" & cues$chilltime==1),] # just guessing!
cues <- cues[!(cues$datasetID=="guerriero90" & cues$study=="exp2" & cues$numcues==0 & cues$field.sample==1),]
cues <- cues[!(cues$datasetID=="spiers74" & cues$study=="exp1" &  cues$numcues==0 & cues$field.sample==1),]
cues <- cues[!(cues$datasetID=="worrall67" & cues$study=="exp 3" & cues$chill==0),] # just guessing!
cues <- cues[!(cues$datasetID=="falusi97" & cues$study=="exp1" & cues$chill==0),] # just guessing!
cues <- cues[!(cues$datasetID=="falusi97" & cues$study=="exp2" & cues$chill==0),] # just guessing!
cues <- cues[!(cues$datasetID=="jones12" & cues$numcues==0),] # I don't think row of code does anything, try cues[(cues$datasetID=="jones12" & cues$numcues==0),]
cues <- cues[!(cues$datasetID=="sonsteby14" & cues$numcues==0),] # What is up with exp5? Why are we just deleting it?
cues <- cues[!(cues$datasetID=="thielges" & cues$numcues==0),] # again,  I don't think row of code does anything
cues <- cues[!(cues$datasetID=="granhus09" & cues$numcues==0),] # checked paper, it has mild spells in chilling
cues <- cues[!(cues$datasetID=="rinne94" & cues$numcues==0),] # checked paper, I think it has two chill levels?

# Which studies still have multiple values?
checkcues <- subset(cues, select=c("datasetID", "study", "numcues"))
checkcuesagg <- aggregate(cues["numcues"], cues[c("datasetID", "study")], FUN=length)
subset(checkcuesagg, numcues>1)

# Now clean up duplicate rows again
cues <- cues[!duplicated(cues),]
}
```

**Comment by lizzieinvancouver** [comment] 2021-02-21 04:16
And more ... including my confused comments from earlier today ...

```
## Okay now, to bring in the info on cues manipulated:
## Why do we need this? And what do the numbers mean? For example, caffarra11a  exp1 says force = 6 but that study has one forcing temperature and it's 22 C ...
# checkdat <- subset(dat, datasetID=="caffarra11a" & study=="exp1")
# unique(checkdat$forcetemp)
if(FALSE){
ospcues <- within(dat, { force <- as.numeric(ifelse(forcetemp!=0, ave(forcetemp, datasetID, FUN=function(x) length(unique(x))), 0))}) # mult forcetemp
ospcues <- within(ospcues, { photo <- as.numeric(ifelse(photoperiod_day!=0, ave(photoperiod_day, datasetID, FUN=function(x) length(unique(x))), 0))}) # mult photoperiod_day
ospcues <- within(ospcues, { chill <- as.numeric(ifelse(chilltemp!=0, ave(chilltemp, datasetID, FUN=function(x) length(unique(x))), 0))}) # mult studychill
ospcues <- within(ospcues, { chilltime <- as.numeric(ifelse(chilldays!=0, ave(chilldays, datasetID, FUN=function(x) length(unique(x))), 0))}) # mult studychill

ospcues <- subset(ospcues, select=c("datasetID", "study", "force", "photo", "chill", "chilltime"))
ospcues$chill <- ifelse(ospcues$chill > 1 | ospcues$chilltime>1, ospcues$chill + ospcues$chilltime, ospcues$chill)
ospcues$chilltime <- NULL
ospcues <- ospcues[!duplicated(ospcues),]

lookupcues <- aggregate(ospcues[c("force", "photo", "chill")], ospcues[c("datasetID", "study")], FUN=sum)


### Look into no interaction studies a little ...
nointxns <- lookupintxns[(lookupintxns$interaction==0),]
nointxns.lookup <- merge(lookupcues, nointxns, by=c("datasetID", "study")) # is this necessary? If so, why?
lookupcues[which(lookupcues$datasetID %in% nointxns$datasetID),]

numnointxnstudies <- length(unique(paste(nointxns.lookup$datasetID, nointxns.lookup$study)))

wintxns <- lookupintxns[(lookupintxns$interaction>0),]
numwintxnstudies <- length(unique(paste(wintxns$datasetID, wintxns$study)))

# Safety check, should be true....
numnointxnstudies+numwintxnstudies==length(unique(paste(lookupintxns$datasetID, lookupintxns$study)))

IDstudybycontinent <- merge(studybycontinent, ospcues, by="datasetID")
IDstudybycontinent <- IDstudybycontinent[!duplicated(IDstudybycontinent),]
}
```

**Comment by lizzieinvancouver** [comment] 2021-02-21 04:25
Can we confirm these studies are exp chill?

```
> notfieldsample
      datasetID study force photo chill chilltime year spp field.sample numcues chillany intxn interaction
6         boyer  exp1     0     0     1         1 1984   1            1       1        1  <NA>           0
12  caffarra11b  exp3     0     0     1         1 2005   1            1       1        1  <NA>           0
14   campbell75  exp1     0     0     1         1 1974   1            1       1        1  <NA>           0
16    cannell83  exp1     0     0     1         1 1974   1            1       1        1  <NA>           0
17    cannell83  exp2     0     0     1         1 1974   1            1       1        1  <NA>           0
20  chavarria09  exp1     0     0     1         1 2005   1            1       1        1  <NA>           0
21  chavarria09  exp2     0     0     1         1 2005   1            1       1        1  <NA>           0
24     cronje03  exp1     0     0     1         1 2001   1            1       1        1  <NA>           0
41    granhus09  exp1     0     0     1         1 2006   1            1       1        1  <NA>           0
44  guerriero90  exp2     0     0     1         1 1990   1            1       1        1  <NA>           0
49      Heide03  exp1     0     0     1         1   NA   3            1       1        1  <NA>           0
69      jones12  exp1     0     0     1         1 2008   1            1       1        1  <NA>           0
70      jones12  exp2     0     0     1         1 2009   1            1       1        1  <NA>           0
76         li05  exp1     0     0     1         1 2004   1            1       1        1  <NA>           0
99      rinne94  exp1     0     0     1         1 1991   1            1       1        1  <NA>           0
100     rinne97  exp1     0     0     1         1 1994   1            1       1        1  <NA>           0
110   sogaard08 exp1b     0     0     1         1 2003   1            1       1        1  <NA>           0
113   sogaard08 exp3b     0     0     1         1 2004   1            1       1        1  <NA>           0
116  sonsteby14  exp1     0     0     1         1 2011   1            1       1        1  <NA>           0
117  sonsteby14  exp2     0     0     1         1 2012   1            1       1        1  <NA>           0
118  sonsteby14  exp3     0     0     1         1 2012   1            1       1        1  <NA>           0
119  sonsteby14  exp4     0     0     1         1 2013   1            1       1        1  <NA>           0
121    spiers74  exp1     0     0     1         1 1973   1            1       1        1  <NA>           0
123    swartz81  exp1     0     0     1         1 1980   1            1       1        1  <NA>           0
124  thielges75  exp1     0     0     1         1   NA   1            1       1        1  <NA>           0
128      webb78  exp1     0     0     1         1 1974   3            1       1        1  <NA>           0
131   worrall67 exp 4     0     0     1         1 1966   1            1       1        1  <NA>           0
```

**Comment by lizzieinvancouver** [comment] 2021-02-21 04:44
@cchambe12 Okay, this is just SO painful. So many hours of my life gone, and now so many of your hours of your life gone ... 

My takehome is that I think our numbers were weird because 'single cue' studies were actually just 'no interaction' studies in your code -- so we were thinking of different things. There were also a lot of dataframes with duplicate rows per datasetID x study and some of the fixes for this were not good so were leading to numbers that did not add up. I also tried to avoid using 'nrow' for that reason ... but even then we need to keep the dataframes super tidy.  I also tried to add some 'safety' checks ... we should probably add more. 

**Sadly, I still need help! In the next week or two could you:**

1. Review the new countinxns code closely to see if it makes sense to you. Check out the deleted code above and some in the R file still and let me know if they do anything special we might want and don't have.
2. Check if the above studies (notfieldsample) are really all expchill. If some are not, make a note here of what they are and I will try to fix. 
3. The below studies show up as three cues ... but I could use a double-check on how best to describe okie11  exp2,  partanen98  exp3, schnabel87  exp1 (are force and photo varied but not full factorial?), and  sogaard08  exp2 
4. Are there any other studies to delete? I set it up to delete spann04, but what about rinne94 and granhus09? What do you think?
5. Could you get the number of papers and studies that include a crop?

```
> threecuesdf 
     datasetID study force photo chill chilltime year spp field.sample numcues chillany
4     basler14  exp1     1     1     1         1 2010   4            3       3        1
62     heide93  exp1     1     1     0         0 1990   6            5       2        1
63     heide93  exp2     1     1     0         0 1991   6            7       2        1
87      okie11  exp2     1     1     1         1 2009   1            1       3        1
92  partanen98  exp1     1     1     1         1 1994   1            2       3        1
94  partanen98  exp3     1     1     1         1 1994   1            2       3        1
106 schnabel87  exp1     1     1     1         1 1984   1           16       3        1
111  sogaard08  exp2     1     1     1         1 2004   1            1       3        1
130  worrall67 exp 3     1     1     1         1 1966   1            1       3        1
                                                                        intxn interaction
4                                          photo x force x field sample dates           1
62                                         photo x force x field sample dates           1
63                                         photo x force x field sample dates           1
87                                                 photo x force x chill days           1
92  photo/force x field sample dates (force and photo are NOT full factorial)           1
94                                                              force x photo           1
106                force/photo x field sample (but mainly field sample dates)           1
111                                                                      <NA>           0
130         photo/force x exp chilldays (force and photo are NOT interactive)           1
```

**Comment by lizzieinvancouver** [comment] 2021-02-21 19:35
I found this in issue #174 ....

For the rest...
granhus09: manipuated dormancy induction temperature
rinne94: different chilling temps for dormancy induction
spann04: percent budburst of flower buds... (I think this needs to be fixed in clean_respvar.R)

I think granhus09 though may be okay as it says "We tested the effects of two temperatures during dormancy induction and mild spells (MS) during chilling on the timing of bud burst in three Picea abies (L.) Karst. provenances (58–66° N)." So some manipulations are during chilling and our data is entered as different chill days. Seems fine to me. 

I am okay leaving in rinne94 also, as it's entered as a well watered and water-stressed set of treatments with all the necessary data. 

Let me know what you think... If we do decide to delete these though, we need to make the change happen EVERYWHERE ... not just for certain R files that you and I are actively working on.

For spann04 I changed to percent flower in cleanmisc.R.

**Comment by cchambe12** [comment] 2021-02-26 16:04
@lizzieinvancouver Okay yes things that I was confused on... 1) I was removing all studies that were not looking at budburst so that's why I had the series of deletions. Some didn't do anything because they were already removed, they were just checks and 2) I also definitely was defining single cues differently in my mind so that explains a lot too. 

1. Your code looks elegant and clean to me! Your notes are very clear and I now really understand what you meant by singlecue. I also learned a lot from your coding so thanks for that!

One question, why are we still deleting spann04? I have no feelings either way I just am not clear on what is the cutoff what experiments we are interested in and which ones we are not. Just because our cutoff is reproductive phenology?

2. I read through the methods of all 27 studies and they are all experimental chill - big relief!

3. Ooof **Okie** is confusing... but looks like it is field chilling with weekly field sample dates but it looks like one cultivar was exposed to varying chill days after being sampled in January. I agree they are testing photoperiod and forcing after that point. **I have updated intxn to read "photo x force x field sample date (and chill days for `Sunland' cultivar)".** 

For partenan98 exp3, I think it's the same as exp1 (`photo/force x field sample dates (force and photo are NOT full factorial)') but the only difference is the field sample dates. **I have updated this one as suggested.**

For schnaebel87, they are testing cold hardiness more and then have constant forcing and photoperiod to evaluate budburst. So many this should be changed to `force/photo x cold hardiness treatment'...? **I updated accordingly but will happily change it to something else if there's another way you would like to define this.**

And for sogaard08 I would say it is `force/photo x chill days'. They have constant forcing with varying photoperiod and chill days. **I have also updated this one.**

4. Looks like you covered this and I agree with your decisions! 

5. Done! I have added two new lines called `numcroppapers' and `numcropstudies' (21 and 34 respectively).

**Comment by lizzieinvancouver** [comment] 2021-03-01 19:42
@cchambe12 Good question about spann04! This is what I had in the code:

`dat <- dat[which(dat$datasetID!="spann04"),] # seems only to treatments during bud formation (I think)
`

And I am re-reading it now. It's hard to tell but I am pretty sure these treatments are NOT applied during dormancy, so I think we should not include it. While we do have a lot of weird treatments, this is the only one I can think of where it seems like the plants might actually be growing (they mention fertilizer, which really makes me wonder) during the treatments, which makes how we would interpret 'forcing' and 'photoperiod' weird. But it's hard to tell.

**Comment by lizzieinvancouver** [comment] 2021-04-03 02:20
@cchambe12 for the cues over time figure:

- Something bad happening to the letter s .. fample dates and fpecies? 
- Based on how the text is written now, I think we lump multiple field sample dates into 1/2/3? (I assume it's studies that only did multiple field sample dates? ) See what you think on reading the next draft.
- Also, please update caption with an important methods or such!

**Comment by cchambe12** [comment] 2021-04-05 15:07
@lizzieinvancouver haha the "f's" were wild, I have no idea what happened there!

Multiple field sample dates are lumped into 1/2/3 cues if chilling is not experimentally manipulated. 

I have updated the caption in a note on the PDF!

**Comment by lizzieinvancouver** [comment] 2021-04-23 23:40
MS submitted, this is done for now ... thank you so much @cchambe12  for help with this very tricky task!

**Closed** 2021-04-23 23:41 UTC
Labels: limiting cues ms
